steps:
  # Paso 1 —imagen usando el commit SHA y el tag 'latest'
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/scorebank-repo/scorebank-api:$COMMIT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/scorebank-repo/scorebank-api:latest"
      - "."

  # Paso 2 - versiones al Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/scorebank-repo/scorebank-api:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/scorebank-repo/scorebank-api:latest"

  # Paso 3 — Aplicar manifiestos de K8s
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - apply
      - "-f"
      - "k8s/"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=scorebank-cluster"

  # Paso 4 — Actualizar la imagen del deployment
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - set
      - image
      - "deployment/scorebank-api"
      - "scorebank-api=us-central1-docker.pkg.dev/$PROJECT_ID/scorebank-repo/scorebank-api:$COMMIT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=scorebank-cluster"


  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - rollout
      - restart
      - "deployment/scorebank-api"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_CONTAINER_CLUSTER=scorebank-cluster"

options:
  logging: CLOUD_LOGGING_ONLY