apiVersion: v1
kind: Secret
metadata:
  name: scorebank-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://scorebank_user:ScoreBank2024!@TU_DB_HOST:5432/scorebank-db"
  API2_URL: "http://podcast-api.duckdns.org"
