apiVersion: v1
kind: Secret
metadata:
  name: scorebank-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://scorebank_user:1h&^R|3#[C(:2&?s@127.0.0.1:5432/scorebank"
  API2_URL: "https://api2-compañero.aws.com"