# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scorebank-service
spec:
  type: LoadBalancer
  selector:
    app: scorebank-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000