apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scorebank-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: scorebank-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s